version: "3.3"
secrets:
  ha_db_user:
    file: $KAREOKE_HOME/secrets/ha_db_user.txt
  ha_db_password:
    file: $KAREOKE_HOME/secrets/ha_db_password.txt
networks:
  kareoke_local:
    external: true
services:
  kareoke-db:
    image: postgres
    restart: always
    container_name: kareoke-db
    secrets:
      - ha_db_user
      - ha_db_password
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/ha_db_password"
      POSTGRES_USER_FILE: "/run/secrets/ha_db_user"
    networks:
      - kareoke_local
    ports:
      - "5432:5432"
    # healthcheck:
    #       test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
    #       timeout: 20s
    #       retries: 10
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
