version: "3"
networks:
  kareoke_local:
    external: true
services:
  "kareoke-ui":
    image: nginx
    container_name: "kareoke-ui"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - 80:80
    networks:
      - kareoke_local
    volumes:
      - "$KAREOKE_HOME/ui/apps:/srv/package"
      - "$KAREOKE_HOME/ui:/ui-config"
      - "$KAREOKE_HOME/ui/apps/ci-helpers:/setup"
      - "$KAREOKE_HOME/local-dev/nginx/certs:/srv/certs"
      - "$KAREOKE_HOME/local-dev/nginx/nginx.conf:/etc/nginx/nginx.conf"
